---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```


```{r include=FALSE}
data("instacart")

instacart = 
  instacart %>%
  select(-add_to_cart_order, -eval_set, -order_number, -days_since_prior_order, -aisle_id, -department_id) %>% 
  sample_n(50000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
```{r echo=FALSE, warning=FALSE}
instacart %>% 
  mutate(
    order_dow = recode(order_dow, "0" = "Sunday", "1" = "Monday", "2" = "Tuesday", "3" = "Wednesday", "4" = "Thursday", "5" = "Friday", "6" = "Saturday"),
    order_dow = factor(order_dow, levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))
    ) %>% 
  group_by(order_dow, order_hour_of_day) %>% 
  summarize(hourly_orders = n()) %>% 
  mutate(
    text_label = str_c("Hour: ", order_hour_of_day, "\nDay: ", order_dow, "\n# of orders: ", hourly_orders)
  ) %>% 
  plot_ly(
    x = ~order_hour_of_day, 
    y = ~hourly_orders, 
    color = ~order_dow, 
    type = "scatter", 
    mode = "line",
    text = ~text_label,
    colors = "viridis") %>% 
  layout(
    title = "Orders by Time of Day",
    xaxis = list(title = "Hour of Day"),
    yaxis = list(title = "Number of Orders")
  )
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r echo=FALSE}
instacart %>%
  count(department) %>% 
  filter(department != "missing") %>% 
  mutate(
    department = fct_reorder(department, n)) %>% 
  plot_ly(
    x = ~department, y = ~n, color = ~department, type = "bar", colors = "magma") %>% 
  layout(
    title = "Orders by Department",
    xaxis = list(title = "Department"),
    yaxis = list(title = "Number of orders"))
```

### Chart C

```{r echo=FALSE}
instacart %>% 
  filter(department == "produce") %>% 
  mutate(aisle = fct_reorder(aisle, order_hour_of_day)) %>%
  plot_ly(x = ~aisle, y = ~order_hour_of_day, color = ~aisle, type = "box", colors = "viridis") %>% 
  layout(
    title = "When shoppers buy their produce", 
    xaxis = list(title = "Produce Aisle"),
    yaxis = list(title = "Hour of Day")
  )
```



